"""Facility-level heat index extraction for Oregon data centers.

Assumptions log
---------------
- Samples the twelve heat rasters already generated by run_heat_processing.py
  (outputs/month2_heat/rasters/*.tif) at each Oregon data center's own
  lon/lat; it does not recompute indices from raw LOCA2 NetCDF, and it does
  not regenerate the rasters -- rerun run_heat_processing.py first if they
  are missing or stale.
- Three periods per the methods doc's "Time Horizons" section: historical
  (1985-2014), mid-century (2045-2074, the primary future period), and
  end-of-century (2075-2100, a conservative secondary period). Deltas are
  computed from historical to each future period separately -- see
  ``docs/tasks/0.2-fix-loca2-window-resolver-and-time-horizons.md``.
- Uses the flat 35C exceedance threshold already baked into those rasters
  for tmax_threshold_days / heatwave_events.
- Elevation-adjusted threshold values (see
  climate_risk_dc.climate.heat_indices.elevation_adjusted_threshold) are NOT
  wired into this table yet: no DEM/elevation raster exists anywhere in this
  repo, so there is no real per-facility elevation to adjust with. Adding an
  adjusted-threshold column here is a follow-up once a DEM source is
  available -- flagged explicitly, not a silent omission.
- Facilities with a null 'name' in the source atlas (a handful of
  Prineville/PDX parcels) are still included; only lon/lat/state_abb are
  required to build the table.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

import pandas as pd

from climate_risk_dc.geo import load_oregon_data_centers, sample_raster_at_points


@dataclass(frozen=True)
class ExtractConfig:
    """Configuration for facility-level heat index extraction."""

    output_name: str = "facility_heat_indices.csv"


PERIOD_LABELS: dict[str, str] = {
    "historical": "historical_1985_2014",
    "mid_century": "ssp585_2045_2074",
    "end_of_century": "ssp585_2075_2100",
}

INDEX_NAMES: tuple[str, ...] = ("cdd", "tmax_threshold_days", "heatwave_events")


def _raster_paths(out_dir: Path) -> dict[str, Path]:
    """Column name -> raster path, matching run_heat_processing.py's naming."""
    raster_dir = out_dir / "rasters"
    return {
        f"{index}_{label}": raster_dir / f"{index}_{label}.tif"
        for label in PERIOD_LABELS.values()
        for index in INDEX_NAMES
    }


def extract_facility_heat_indices(root: Path, cfg: ExtractConfig = ExtractConfig()) -> pd.DataFrame:
    """Sample the six existing heat rasters at each Oregon DC's own coordinates.

    Raises
    ------
    FileNotFoundError
        If a required raster hasn't been generated yet.
    ValueError
        If any facility samples as NaN for any raster (outside the raster
        extent or on a nodata cell) -- rather than silently emitting a NaN
        row, per the close-out task's acceptance check.
    """
    out_dir = root / "outputs" / "month2_heat"
    dc_csv = (
        root / "data" / "data_centers_im3_pnnl" / "im3_open_source_data_center_atlas_v2026.02.09.csv"
    )

    dc = load_oregon_data_centers(dc_csv)
    lon = dc["lon"].to_numpy()
    lat = dc["lat"].to_numpy()

    result = pd.DataFrame(
        {
            "facility_id": dc["id"].to_numpy(),
            "facility_name": dc["name"].to_numpy(),
            "facility_lon": lon,
            "facility_lat": lat,
        }
    )

    for col, raster_path in _raster_paths(out_dir).items():
        if not raster_path.exists():
            raise FileNotFoundError(
                f"Expected heat raster not found: {raster_path}. "
                "Run scripts/run_heat_processing.py first."
            )
        result[col] = sample_raster_at_points(raster_path, lon, lat)

        missing = result.loc[result[col].isna(), "facility_id"]
        if not missing.empty:
            raise ValueError(
                f"{len(missing)} facility(ies) sampled as NaN for '{col}' "
                f"(outside raster extent or on a nodata cell): {missing.tolist()}"
            )

    hist_label = PERIOD_LABELS["historical"]
    for period_key in ("mid_century", "end_of_century"):
        label = PERIOD_LABELS[period_key]
        for index in ("tmax_threshold_days", "heatwave_events"):
            result[f"{index}_{period_key}_delta"] = (
                result[f"{index}_{label}"] - result[f"{index}_{hist_label}"]
            )

    return result


def run(args: argparse.Namespace) -> None:
    root = Path(args.repo_root).resolve()
    cfg = ExtractConfig()
    result = extract_facility_heat_indices(root, cfg)

    out_dir = root / "outputs" / "month2_heat"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / cfg.output_name
    result.to_csv(out_path, index=False)

    print(f"Wrote {len(result)} facility rows to {out_path}")
    for period_key in ("mid_century", "end_of_century"):
        neg_days = int((result[f"tmax_threshold_days_{period_key}_delta"] < 0).sum())
        neg_events = int((result[f"heatwave_events_{period_key}_delta"] < 0).sum())
        print(
            f"Sanity check ({period_key}): {neg_days} facilities with negative "
            f"tmax_threshold_days_delta, {neg_events} with negative heatwave_events_delta "
            "(expect 0 for both under SSP585)."
        )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sample existing heat rasters at Oregon data-center coordinates."
    )
    parser.add_argument(
        "--repo-root",
        default=".",
        help="Repository root path (default: current directory)",
    )
    return parser.parse_args()


if __name__ == "__main__":
    run(parse_args())
