"""Facility-level heat index extraction for Oregon data centers.

Assumptions log
---------------
- Samples the six heat rasters already generated by run_heat_processing.py
  (outputs/month2_heat/rasters/*.tif) at each Oregon data center's own
  lon/lat; it does not recompute indices from raw LOCA2 NetCDF, and it does
  not regenerate the rasters -- rerun run_heat_processing.py first if they
  are missing or stale.
- Uses the flat 35C exceedance threshold already baked into those rasters
  for tmax_threshold_days / heatwave_events.
- Elevation-adjusted threshold values (see
  climate_risk_dc.climate.heat_indices.elevation_adjusted_threshold) are NOT
  wired into this table yet: no DEM/elevation raster exists anywhere in this
  repo, so there is no real per-facility elevation to adjust with. Adding an
  adjusted-threshold column here is a follow-up once a DEM source is
  available -- flagged explicitly, not a silent omission.
- Facilities with a null 'name' in the source atlas (a handful of
  Prineville/PDX parcels) are still included; only lon/lat/state_abb are
  required to build the table.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

import pandas as pd

from climate_risk_dc.geo import load_oregon_data_centers, sample_raster_at_points


@dataclass(frozen=True)
class ExtractConfig:
    """Configuration for facility-level heat index extraction."""

    output_name: str = "facility_heat_indices.csv"


def _raster_paths(out_dir: Path) -> dict[str, Path]:
    """Column name -> raster path, matching run_heat_processing.py's naming."""
    raster_dir = out_dir / "rasters"
    return {
        "cdd_historical_1950_1979": raster_dir / "cdd_historical_1950_1979.tif",
        "tmax_threshold_days_historical_1950_1979": raster_dir
        / "tmax_threshold_days_historical_1950_1979.tif",
        "heatwave_events_historical_1950_1979": raster_dir / "heatwave_events_historical_1950_1979.tif",
        "cdd_ssp585_2070_2099": raster_dir / "cdd_ssp585_2070_2099.tif",
        "tmax_threshold_days_ssp585_2070_2099": raster_dir / "tmax_threshold_days_ssp585_2070_2099.tif",
        "heatwave_events_ssp585_2070_2099": raster_dir / "heatwave_events_ssp585_2070_2099.tif",
    }


def extract_facility_heat_indices(root: Path, cfg: ExtractConfig = ExtractConfig()) -> pd.DataFrame:
    """Sample the six existing heat rasters at each Oregon DC's own coordinates.

    Raises
    ------
    FileNotFoundError
        If a required raster hasn't been generated yet.
    ValueError
        If any facility samples as NaN for any raster (outside the raster
        extent or on a nodata cell) -- rather than silently emitting a NaN
        row, per the close-out task's acceptance check.
    """
    out_dir = root / "outputs" / "month2_heat"
    dc_csv = (
        root / "data" / "data_centers_im3_pnnl" / "im3_open_source_data_center_atlas_v2026.02.09.csv"
    )

    dc = load_oregon_data_centers(dc_csv)
    lon = dc["lon"].to_numpy()
    lat = dc["lat"].to_numpy()

    result = pd.DataFrame(
        {
            "facility_id": dc["id"].to_numpy(),
            "facility_name": dc["name"].to_numpy(),
            "facility_lon": lon,
            "facility_lat": lat,
        }
    )

    for col, raster_path in _raster_paths(out_dir).items():
        if not raster_path.exists():
            raise FileNotFoundError(
                f"Expected heat raster not found: {raster_path}. "
                "Run scripts/run_heat_processing.py first."
            )
        result[col] = sample_raster_at_points(raster_path, lon, lat)

        missing = result.loc[result[col].isna(), "facility_id"]
        if not missing.empty:
            raise ValueError(
                f"{len(missing)} facility(ies) sampled as NaN for '{col}' "
                f"(outside raster extent or on a nodata cell): {missing.tolist()}"
            )

    result["tmax_threshold_days_delta"] = (
        result["tmax_threshold_days_ssp585_2070_2099"]
        - result["tmax_threshold_days_historical_1950_1979"]
    )
    result["heatwave_events_delta"] = (
        result["heatwave_events_ssp585_2070_2099"] - result["heatwave_events_historical_1950_1979"]
    )

    return result


def run(args: argparse.Namespace) -> None:
    root = Path(args.repo_root).resolve()
    cfg = ExtractConfig()
    result = extract_facility_heat_indices(root, cfg)

    out_dir = root / "outputs" / "month2_heat"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / cfg.output_name
    result.to_csv(out_path, index=False)

    print(f"Wrote {len(result)} facility rows to {out_path}")
    neg_days = int((result["tmax_threshold_days_delta"] < 0).sum())
    neg_events = int((result["heatwave_events_delta"] < 0).sum())
    print(
        f"Sanity check: {neg_days} facilities with negative tmax_threshold_days_delta, "
        f"{neg_events} with negative heatwave_events_delta (expect 0 for both under SSP585)."
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sample existing heat rasters at Oregon data-center coordinates."
    )
    parser.add_argument(
        "--repo-root",
        default=".",
        help="Repository root path (default: current directory)",
    )
    return parser.parse_args()


if __name__ == "__main__":
    run(parse_args())
